#!/opt/homebrew/bin/bash -eu

# Get today's date
date=$(date +"%F")                      # YYYY-MM-DD
week=$(date +"%U")			# Sunday is the first day


# Define the file path
slug="week_${week,,}"                   # lower-case
file_path="_posts/${date}-${slug}.md"
title="What I've done this week."

# Create the new markdown file with front matter
cat <<EOL > $file_path
---
title: "${title}"
slug: "${slug}"
date: "${date}"
layout: post
---

* Five-bullet summary
* General geeking
* Math
* Health, mental & physical
* Music
* Misc

EOL

echo "New post created at $file_path"
vim +$ $file_path
